# Generated by Django 3.2.3 on 2021-08-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_register_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
    ]
