# Generated by Django 3.2.3 on 2021-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('suggestion', models.CharField(max_length=200)),
                ('shift', models.CharField(max_length=50)),
                ('meeting', models.CharField(max_length=50)),
                ('overall', models.CharField(max_length=50)),
            ],
        ),
    ]
