# Generated by Django 3.2.3 on 2021-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_srs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=50)),
            ],
        ),
    ]
